Repository k8s-crafts/ephemeral-containers-plugin, pull requests merged in 2024-10, with the labels that each got.

#1 ci(lint): add lint ci workflow
  .github/workflows/lint.yaml
Labels: ci, feat

#2 feat(plugin): complete v1 implementations
  .github/workflows/test.yaml
  Makefile
  cmd/ephemeral-containers/edit.go
  cmd/ephemeral-containers/list.go
  cmd/ephemeral-containers/root.go
  cmd/ephemeral-containers/version.go
  main.go
  pkg/edit/editor.go
  pkg/edit/editor_test.go
  pkg/flags/flags.go
  pkg/formatter/formatter.go
  pkg/formatter/formatter_test.go
  pkg/k8s/client.go
  pkg/k8s/pods.go
  pkg/out/out_test.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: feat, size/XL

#3 feat(plugin): prepare major stable release v1
  .github/workflows/lint.yaml
  .golangci.yaml
  .goreleaser.yaml
  Makefile
  README.md
  cmd/ephemeral-containers/edit.go
  cmd/ephemeral-containers/list.go
  cmd/ephemeral-containers/root.go
  cmd/ephemeral-containers/version.go
  main.go
  pkg/edit/editor_test.go
  pkg/formatter/formatter.go
  pkg/formatter/formatter_test.go
  pkg/k8s/namespace.go
  pkg/version/version.go
  pkg/version/version_generated.go
  pkg/version/version_test.go
  tools/version_generator.go
Labels: feat, size/XL

#10 docs(contributing): add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: kind/community-docs

#8 docs(contributing): add guides for on-boarding new contributors
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Makefile
  README.md
  docs/DEVELOPER_GUIDES.md
  docs/USER_GUIDES.md
  pkg/version/version_generated.go
Labels: kind/community-docs

#12 fix(make): golangci-lint should be installed if missing
  Makefile
Labels: kind/code-cleanup

#15 Add Pull Request template
  .github/pull_request_template.md
Labels: kind/community-docs, hacktoberfest-accepted

#16 Increase linter timeout
  .golangci.yaml
Labels: kind/ci, hacktoberfest-accepted, kind/fix

#17 docs(contributing): contributors are required to sign commits
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: kind/community-docs

#18 Display test coverage summary
  .github/workflows/test.yaml
Labels: kind/ci, kind/feat, hacktoberfest-accepted

#26 use kind/build label
  .github/dependabot.yml
Labels: kind/ci, hacktoberfest-accepted, kind/fix

#28 fix(kubeconfig): namespace of active kube context should be honored
  cmd/root.go
Labels: kind/code-cleanup, kind/fix

#29 test(e2e): e2e tests for plugin
  .github/workflows/test.yaml
  .gitignore
  Makefile
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
  e2e/testdata/pod.yaml
  e2e/testdata/serviceaccount.yaml
  e2e/testutils/misc.go
  e2e/testutils/utils.go
  go.mod
  go.sum
  scripts/e2e_cleanup.sh
  scripts/e2e_setup.sh
Labels: dependencies, test/e2e

#32 test(e2e): add test cases for output format and help cmd
  cmd/edit.go
  cmd/list.go
  cmd/version.go
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
  e2e/testdata/pod.yaml
  e2e/testdata/serviceaccount.yaml
  e2e/testutils/resources.go
  e2e/testutils/utils.go
Labels: kind/code-cleanup, test/e2e, test/coverage
